-- Table: questions
CREATE TABLE public.questions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    lesson_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    explain TEXT DEFAULT '',
    is_mcq BOOLEAN,
    h_url TEXT,
    q_url TEXT,
    is_visible BOOLEAN DEFAULT true,
    FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
