-- Table: question_categories
CREATE TABLE public.question_categories (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title TEXT NOT NULL UNIQUE,
    sort_order INTEGER DEFAULT 0,
	
	is_orderable BOOLEAN NOT NULL DEFAULT FALSE,
	is_typeable BOOLEAN NOT NULL DEFAULT FALSE,
	is_mcq BOOLEAN NOT NULL DEFAULT FALSE,
	is_single_answer BOOLEAN NOT NULL DEFAULT FALSE,
	
	created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: questions
CREATE TABLE public.questions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    image_url TEXT DEFAULT NULL,
    lesson_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES public.question_categories(id) ON DELETE CASCADE
);

-- Table: question_options
CREATE TABLE public.question_options (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    is_correct BOOLEAN DEFAULT false,
    sort_order INTEGER NULL,
    question_id INTEGER NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE
    
);

-- Table: question_answers
CREATE TABLE public.question_answers (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    result_id BIGINT NOT NULL,
    question_id INTEGER NOT NULL,
    option_id INTEGER NULL,          
    answer_text TEXT NULL,           
    answer_position INTEGER NULL,
	is_correct BOOL not null default false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (result_id) REFERENCES public.results(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE RESTRICT,
    FOREIGN KEY (option_id) REFERENCES public.question_options(id) ON DELETE SET NULL
);

-- Table: answer_evaluations
CREATE TABLE public.answer_evaluations (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    question_answer_id BIGINT NOT NULL,
    -- note: this could lead to conflicts.
    is_correct BOOLEAN NOT NULL,           -- this evaluation's judgment
    confidence NUMERIC(5,2) NULL,          -- 0–100 scale or 0–1 depending on your choice
    notes TEXT NULL,                       -- explanation / reasoning
    model_name TEXT NULL,                  -- if AI, store which model was used
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (question_answer_id) REFERENCES public.question_answers(id) ON DELETE CASCADE
);

